language: java

# Nothing to install
install: true

# Sonar Integration
addons:
  sonarcloud:
    organization: "romainj1-github"

# Build step
script:
  - ./compile.sh
  - sonar-scanner -Dsonar.java.binaries=./classes


notifications:
  email: false
